### PR TITLE
Add Denarius (DNR)

### PR DESCRIPTION
**Pull request by metaspartan**
Added support for DNR, to my knowledge. If something is missing, let me know!

### CODE REVIEW

**Review by pbca26 — COMMENTED** [review]
but why? why changing the repo?

**Comment by carsenk** [comment]
Well someone in the Slack told me the correct branch was v0.25 but I can move back to master or wherever you would like it! :)

**Comment by metaspartan** [comment]
Oops though didn't mean to commit the branch changes to the submodule

**Comment by metaspartan** [comment]
Alright, should be good now, GUI PR is here: https://github.com/SuperNETorg/EasyDEX-GUI/pull/196

**Comment by metaspartan** [comment]
Okay we should be 100% good haha. Sorry about that, only changed submodule on my own branch didn't realized I committed was doing testing. Let me know if you need anything else from me.

**Comment by pbca26** [comment]
@carsenk your electrums don't seem to respond

(echo '{ "id": 1, "method": "blockchain.address.get_balance", "params": ["17p7mv3naiNnQFJQ8399QWUj32jZze99RW"] }'; sleep 0.5) | ncat 173.254.244.122 50002
(echo '{ "id": 1, "method": "blockchain.address.get_balance", "params": ["17p7mv3naiNnQFJQ8399QWUj32jZze99RW"] }'; sleep 0.5) | ncat 173.254.244.119 50002

**Comment by metaspartan** [comment]
I just verified both Electrum servers are online still...

r 08 15:26:14 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:flush #7,331 took 0.3s.  Height 621,762 txs: 
1,112,130                                                  
Mar 08 15:26:14 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:processed 1 block in 0.3s                    
^[[BMar 08 15:26:48 denarius electrumx_server.py[22018]: IN
FO:Prefetcher:new block height 621,763 hash 000000000001260
1050e2ba577fec9cd22cca43a0738aa10b9ab212ca2aef7ea          
Mar 08 15:26:48 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:flush #7,332 took 0.0s.  Height 621,763 txs: 
1,112,131                                                  
Mar 08 15:26:48 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:processed 1 block in 0.0s                    
Mar 08 15:26:53 denarius electrumx_server.py[22018]: INFO:M
emPool:0 txs touching 0 addresses                          
aMar 08 15:27:03 denarius electrumx_server.py[22018]: INFO:
Prefetcher:new block height 621,764 hash 0000000000004b8088
bd1ee3a8505fff40b0db0c44fc6cea3307439119da65d6             
Mar 08 15:27:03 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:flush #7,333 took 0.0s.  Height 621,764 txs: 
1,112,132                                                  
Mar 08 15:27:03 denarius electrumx_server.py[22018]: INFO:B
lockProcessor:processed 1 block in 0.0s

**Comment by pbca26** [comment]
i'm not getting any responses from your servers at all
not even an error

this is an example what i get from kmd electrum
(echo '{ "id": 1, "method": "blockchain.address.get_balance", "params": ["RDbGxL8QYdEp8sMULaVZS2E6XThcTKT9Jd"] }'; sleep 0.5) | ncat electrum1.cipig.net 10001
{"jsonrpc": "2.0", "id": 1, "result": {"confirmed": 148130, "unconfirmed": 0}}

can you verify your servers work? you can use any electrum method / address and ncat to get a response

**Comment by metaspartan** [comment]
Have you tried port 50001?

They seem to work fine with that port, though I do have SSL enabled on both and port 50002 should work but I can't seem to get a response from that port:
 curl 173.254.244.119:50001
{"jsonrpc": "2.0", "id": null, "error": {"message": "cannot decode JSON: Expecting value: line 1 column 1 (char 0)", "code": -32700}}

**Comment by pbca26** [comment]
173.254.244.119:50002 that's what you committed
50001 works

**Comment by metaspartan** [comment]
Updated ports for now until I get 50002 working properly.

**Pull request closed without merging**
